fieldLayouts:
  5b8ac1fd-0c2f-41a3-9609-9e80ff4d6951:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: b7ea7e0b-0642-4549-a3f3-9cf9d1bbcc5b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: logos
hasUrls: true
name: Logos
settings:
  path: '@baseAssets/images/logos'
sortOrder: 2
type: craft\volumes\Local
url: '@baseUrl/public/images/logos'
