contentColumnType: text
fieldGroup: 1b319963-ca91-457b-aa8a-1f5f0f06780c
handle: optimizedimages
instructions: ''
name: OptimizedImages
searchable: false
settings:
  displayDominantColorPalette: '1'
  displayLazyLoadPlaceholderImages: '1'
  displayOptimizedImageVariants: '1'
  ignoreFilesOfType:
    - image/svg
  variants:
    -
      __assoc__:
        -
          - width
          - '1920'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '1600'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '1400'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '1200'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '1024'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '992'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '768'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '60'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '60'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
